### ISSUE TITLE
Actor.onKeyUp() and Actor.onKeyDown() extension functions

### ISSUE THREAD

**Issue by andrejp88** [czyzby/ktx#24]
onKey() is all fine and well, but it has a couple of downsides.
- It only supports letter/number keys - you can't e.g. bind Esc to close a menu.
- Holding down a key will continuously fire events instead of just one, on the initial key-down.
- Doesn't detect key releases.

The proposed functions would bind an InputListener with the onKeyDown() or onKeyUp() methods overriden.

**Comment by czyzby** [comment]
Thanks for the suggestion.
