### ISSUE TITLE
Update Kotlin to 1.1.1

### ISSUE THREAD

**Issue by sreich** [czyzby/ktx#30]
1.1.1 is now out, we can update to it.

**Comment by czyzby** [comment]
Fortunately, I don't think there were any breaking changes. As long as you use a build tool like Gradle or Maven, you should have no problem upgrading to Kotlin 1.1.1 with current KTX libraries - the build tool should automatically prefer the newer Kotlin library version over the 1.1.0 that KTX currently uses.

Anyway, thanks for the reminder - the next release will be up to date.
