### ISSUE TITLE
improving scene2d label,textbutton property notation for setting text

### ISSUE THREAD

**Issue by sreich** [czyzby/ktx#36]
this is something that's been bothering me...

so you know how kotlin transforms get/set methods from java into property accessors. well, one place this screws up is in label and textbutton of scene2d.

`label.text = "test" // won't work, can't assign string to stringbuilder`

this exists because label has getText():StringBuilder, and setText(String)..which is a bit strange of an api to begin with.

in other words, from what i've seen, your only way of setting text is:

`label.setText("")`

the only workaround i could think of is something like this...(both textbutton and label are affected, not sure what else..haven't looked

```
private var Label.label: String
    get() = text.toString()
    set(str) = setText(str)
```

```
private var TextButton.label: String
    get() = text.toString()
    set(str) = setText(str)
```

got any better ideas? i really don't like the method syntax, property syntax is much more straightforward esp when everything else uses it (consistency). i have yet to find other properties that have similar problems.

**Comment by czyzby** [comment]
`txt`? `value`? `data`? Maybe `text` will _just work_ (TM) if I throw enough extensions at `Label`. I'll try to improve its API.

**Comment by czyzby** [comment]
`TextButton` already has a label getter and it would be pretty misleading in `Label` widget, so I'm not sure about `label` property. `data` and `value` are too vague (and `data` is a keyword, hah). `txt` is not perfect either, but it's pretty readable and has a similar name to the original field. I think I'll go with that - if you have any ideas, we can still change this before the next release.

**Comment by sreich** [comment]
Yes I'm leaning towards txt as well, it's the best option imo(label was just a 5am example). 


Really wish there were a better way, but unfortunately kotlin won't let you shadow, even if you're really really sure you want to due to bad api, as in this case.

**Comment by czyzby** [comment]
Done. `label.txt` and `textButton.txt` can be used to both access the text fields (converted to `String`) and change them with the property syntax (again, consuming `String` for compatibility). Snapshot release should be available soon.

**Comment by sreich** [comment]
Nice work, thanks

**Comment by czyzby** [comment]
There are a lot of similar cases where Kotlin compiler cannot properly generate properties correctly - like in case of setter methods without corresponding getters (for example - `Label.setWrap`). Most of these are rather obscure - I don't think it's worth the time covering all of these, especially since we might not be so lucky with the naming in every case. However, if you noticed that a particular missing property seems annoying, don't hesitate to open another issue. Thanks.
