### ISSUE TITLE
Refactoring Vis module

### ISSUE THREAD

**Issue by kotcrab** [czyzby/ktx#44]
This is attempt to improve current Vis builder API. Current implementation when building actors that belong to `Table`-type widget will return `Cell<Actor>` which is convenient if you need to modify cell properties but most of the time you also need to get `Actor` itself which requires not so convenient `.actor` call.
New API will introduce `.cell {}` that will allow to modify `Cell` properties but still return `Actor`.

This requires to re-purpose `Actor.userObject` for storing Cell. However `.cell {}` syntax is only valid in UI builder, allowing user to re user field later. Also, fallback method searching actor hierarchy search would be implemented.

 `.cell {}` syntax is only valid in current DSL block thanks to two things:
- only parental Actors that will put Cell instance in `Actor.userObject` provide API to call `.cell{}` (thanks to possibility to put extension methods in interface)
- nested DSL blocks won't be able to call it thanks to `@DslMarker` annotation

This is simple subset of current API with those changes implemented. Notice that there is only one `WidgetFactory` interface for both `Table`-type and standard `WidgetGroup` actors. Usage of `@DslMarker` requires to extend all widget classes such as `VisLabel`, that was not needed before.

```kotlin
inline fun table(init: KVisTable.() -> Unit): Table = actor(KVisTable(), init)

inline fun horizontalGroup(init: KHorizontalGroup.() -> Unit): KHorizontalGroup = actor(KHorizontalGroup(), init)

inline fun <T : Actor> actor(actor: T, init: T.() -> Unit): T {
    actor.init()
    return actor
}

@VisDslMarker
class KVisLabel(text: CharSequence, styleName: String) : VisLabel(text, styleName)

@VisDslMarker
class KVisTable : VisTable(false), WidgetFactory, CellAccessor {
    override fun <T : Actor> addActorToWidgetGroup(actor: T): T {
        val cell = add(actor)
        actor.userObject = cell
        return actor
    }
}

@VisDslMarker
class KHorizontalGroup : HorizontalGroup(), WidgetFactory {
    override fun <T : Actor> addActorToWidgetGroup(actor: T): T {
        addActor(actor)
        return actor
    }
}

interface CellAccessor {
    fun <T : Actor> T.cell(): Cell<T> {
        return this.userObject as Cell<T> //TODO fallback to actor hierarchy search
    }

    fun <T : Actor> T.cell(initCell: Cell<T>.() -> Unit): T {
        cell().initCell()
        return this
    }

    // Alternatively to above
    fun <T : Actor> T.cell(grow: Boolean, padding: Float = 0f /* other fields ...*/): T {
        if (grow) cell().grow()
        cell().pad(padding)
        return this
    }

    fun <T : Actor> T.row(): T {
        cell().row()
        return this
    }


    @Deprecated("Calls to cell() can't be nested", level = DeprecationLevel.ERROR)
    fun <T : Actor> Cell<T>.cell() {
    }

    @Deprecated("Calls to cell() can't be nested", level = DeprecationLevel.ERROR)
    fun <T : Actor> Cell<T>.cell(initCell: Cell<T>.() -> Unit) {
    }
}


interface WidgetFactory {
    fun label(text: String, styleName: String = DEFAULT_STYLE, init: KVisLabel.() -> Unit = {}): VisLabel
            = actor(KVisLabel(text, styleName), init)

    fun table(init: KVisTable.() -> Unit = {}): VisTable = actor(KVisTable(), init)

    fun horizontalGroup(init: KHorizontalGroup.() -> Unit = {}): HorizontalGroup = actor(KHorizontalGroup(), init)

    fun <T : Actor> actor(actor: T, init: T.() -> Unit): T {
        val result: T = addActorToWidgetGroup(actor)
        actor.init()
        return result
    }

    fun <T : Actor> addActorToWidgetGroup(actor: T): T
}

@DslMarker
annotation class VisDslMarker
```

Usage examples
```kotlin
fun createUI() {
    var extLabel: VisLabel? = null

    table {
        extLabel = label("A")
        val label: VisLabel = label("A") {
            setAlignment(Align.left)
            // cell {} // this is invalid because of DslMarker
        }
        val labelCell: Cell<VisLabel> = label("A").cell() // get cell explicitly
        val label2: VisLabel = label("A").cell { growX() } // modify some values of cell but still get actor
        val label4: VisLabel = label("A").cell(grow = true, padding = 2f) // alternative way to modify cell properties

        horizontalGroup {
            // both invalid because of DslMarker
            // label2.cell()
            // label("A").cell()
        }
    }

    horizontalGroup {
        val label: VisLabel = label("A")
        //label("A").cell() // invalid, IDE won't suggest cell here
    }

    // invalid, IDE won't suggest cell here
    //extLabel.cell()
    //extLabel.cell { growX() }
}

```

@czyzby Any thoughts, do you see any shortcomings of this approach?

**Comment by kotcrab** [comment]
#### Bonus: Fragment API
While builders are great they tend to create nested hell of clousers, this is attempt to prevent this by allowing to easily extract UI pieces to so called fragments.

API declaration:
```kotlin
fun fragment(ui: () -> Actor): VisFragment = object : VisFragment() {
    override val ui = ui()
}

fun tableFragment(buildUi: KVisTable.() -> Unit): VisFragment = object : VisFragment() {
    override val ui = table { buildUi(this) }
}

abstract class VisFragment {
    open val ui: Actor = Actor()
}

fun <T : VisFragment> WidgetFactory.fragment(fragment: T): T {
    actor(fragment.ui, {})
    return fragment
}
```

New extension methods for `CellAccessor`:
```kotlin
    fun <T : VisFragment> T.cell(): Cell<Actor> {
        return this.ui.userObject as Cell<Actor>
    }

    fun <T : VisFragment> T.cell(initCell: Cell<Actor>.() -> Unit): T {
        cell().initCell()
        return this
    }

    fun <T : VisFragment> T.row(): T {
        cell().row()
        return this
    }
```

Usage:
Declaring fragment as class. This won't compile with above subset of new vis api but its taken straight out my project, only changed direct cell modification to new `.cell { }`
```kotlin
class ExampleFragment : VisFragment() {
    lateinit var pakFileView: PakFileView
    lateinit var listView: ListView<File>
    lateinit var fileAdapter: FilteredFileAdapter
    lateinit var filterEntry: VisTextField

    override val ui = table {
        background = VisUI.getSkin().getDrawable("window-bg")
        horizontalGroup {
            label("Filter ")
            filterEntry = textField("")
        }.cell { growX() }.row()

        fileAdapter = FilteredFileAdapter(extension, File(baseFateCPKUnpackPath, "pack").walk().toList())

        table {
            defaults().growY()
            listView = listView(fileAdapter).cell { prefWidth(300f) }
            pakFileView = add(PakFileView()).cell { grow() }
        }.cell { growX() }


        listView.setItemClickListener {
             pakFileView.loadPak(it)
         }
        filterEntry.onChange { changeEvent, field ->
            fileAdapter.filterList(field.text)
        }
    }
}
```

Or just create fragment with method declaration
```kotlin
fun fragmentOnDemand(): VisFragment = tableFragment {
    label("A")
    label("B")
    label("C")
}

fun fragmentOnDemand2(): VisFragment = fragment {
    horizontalGroup {
        label("A")
        label("B")
        label("C")
    }
}
```

Adding fragments to UI:
```kotlin
fun buildUI() {
    table {
        val frag: ExampleFragment = fragment(ExampleFragment()).cell { growX() }.row()
        fragment(fragmentOnDemand()).cell { growX() }
        fragment(fragmentOnDemand2()).cell { growX() }
    }
}
```

### Alternatives

Instead of fragments is possible to just use standard widgets but this creates API like this
```kotlin
class TestTable : VisTable(false) {  // class must be referenced by name
    init {
        table {  // no way to start UI building without call to base builder function

        }
    }
}
```

Function version is similar to fragment though
```kotlin
fun testTableFunction(): Table = table {
    label("A")
}
```

Adding to UI
```kotlin
table {
    actor(TestTable()).cell { growX() }
    actor(testTableFunction()).cell { growX() }
}
```

Other method with exposing K* widgets.
```kotlin
class TestTable2 : KVisTable() { // KVisTable must be made `open` and directly referenced
    init { // no need to call base builder method
        label("A")
    }
}
```

**Comment by czyzby** [comment]
I'm not a fan of manipulating `Cell` properties outside of the building block of the actual actor. This leads to actor properties being scattered at two places.
```Kotlin
table {
  table {
    setTouchable(Touchable.disabled) // 1
    table {
       // More actors...
       // More actors...
       // More actors...
    }
  }.cell(expand = true) // 2
}
```

This might not seem like that big of a deal while the UI is still small, but imagine the table had 8 children. When configuring actors at the bottom of the building block, you visually lose track of what's actually configured - when the actor's properties are at the top of the building block, you automatically associate them with this particular actor. I find the approach of "open building block, configure, add children" more readable and I'd try to refactor VisUI to expose table cells and tree nodes as building block parameters (available as `it`).

```Kotlin
window(title = "Hello world!") {
  button { cell ->
    // Changing button properties - button available as "this":
    color = Color.CORAL
    // Changing cell properties:
    cell.fillX().row()
  }
}
```

**Comment by kotcrab** [comment]
I disagree about losing track of what is actually configured. When creating UI you also have to look how Cell of other elements are configured. In my approach, it ends up in standard place after closing parenthesis, easy to notice. It's on the same indent level as actor declaration, that's makes it easier to see what is configured.
In case of your approach it will end up in the middle of actor configuration and adding more children. 

There is also important factor to consider: should you create such big structures? They will create big nested blocks hard to read anyway. That's why I'm also proposing easier way to extract fragments.

**Comment by czyzby** [comment]
> I disagree about losing track of what is actually configured.

I guess it comes down to preferences and code style. For me, configuring cell properties is not unlike managing the actor's internals - that's why I like to keep it together, close to the actor declaration.

> They will create big nested blocks hard to read anyway. That's why I'm also proposing easier way to extract fragments.

Not sure if the benefits justify introducing another API that the users would have to learn. I think extracting common code to utility file-scope functions would do fine without the additional complexity of another API - this would feel very familiar to introducing custom actor builders. I don't see why you couldn't approach it like this:
```Kotlin
fun KTable.greeting(): Cell<Table> =
  table {
    // Configure some special actors.
  }.cell()

// Usage:
table {
  greeting().expand()
  // Other actors.
}
```

> There is also important factor to consider: should you create such big structures? 

Depends on the application and use case, really. Reusability is one thing, but if you want to separate UI building code into functions for the sake of having 6 methods with 5 lines (that you'll never use again) instead of one building block with 30 lines - that's when I think having it in one place is actually more readable. I think building blocks of complex views up to as much as 60 lines might be acceptable - and that's when you can lose track of things and cells after the blocks are not as readable. Maybe that's because I think of KTX views in terms of a markup language (like HTML) rather than actual application logic - you always configure the HTML tags with attributes in the declaration.

But you know what? The best thing about Kotlin flexibility is that we can use both approaches simultaneously. `cell` method usage would be optional, and lambda parameter could be ignored without consequences. This would allow the users to choose the approach that they prefer, depending on the situation.

```Kotlin
table {
   label("No API clash!") { cell ->
     cell.row()
   }
   label("Yup.").cell(expand = true)
}
```

What do you think?

**Comment by kotcrab** [comment]
> Not sure if the benefits justify introducing another API that the users would have to learn. 

Yeah, that's why I tried to keep API simple. I like the way with extension method, seems better. Fragments was more targetted to help with extracting part of view to separate class that will have some extra fields and methods related to it, avoiding cluttering current class. 

Of course extracting fragments just for the sake of is not useful but in real application you will probably have UI blocks that would be beneficial to have separated. Even if they won't be reusable. For example left section of Vis file chooser with disk list and favourites, it would have some method that update view with new favourites and so on. 

> But you know what? The best thing about Kotlin flexibility is that we can use both approaches simultaneously. 

Well, I guess that just solves this.

**Comment by czyzby** [comment]
> Well, I guess that just solves this.

In fact, now I plan on adding scoped `cell` and `node` methods to children of `Table`/`Tree` widgets to `ktx-scene2d`, although I don't think they should return `Cell`/`Node` instances. Instead, I'll add `cell` _function_ (that allows to configure `Cell` setting with parameters and `cell` _property_ (that returns the actual cell if the user needs it for some reason).

```Kotlin
table {
   val label: Label = label("Cell settings example.").cell(expand = true)
   val cell: Cell<Label> = label("Cell instance reference.").cell
   val combined: Cell<Label> = label("Awkward, but powerful.").cell(expand = true).cell
}
```

This will hopefully blur the difference between `ktx-scene2d` and `ktx-vis` API. Can you investigate if you can easily add support for `Cell` lambda parameter in building blocks of `ktx-vis`?

**Comment by kotcrab** [comment]
> Can you investigate if you can easily add support for Cell lambda parameter in building blocks of ktx-vis?

Kind of 
```kotlin
//WidgetFactory changes
fun label(text: String, styleName: String = DEFAULT_STYLE, init: VisLabel.(R) -> Unit = {}): R

fun <T : Actor> actor(actor: T, init: T.(R) -> Unit): R {
    val result = addActorToWidgetGroup(actor)
    actor.init(result)
    return result
}
//TableWidgetFactory
override fun label(text: String, styleName: String, init: VisLabel.(Cell<*>) -> Unit): Cell<VisLabel>
//WidgetGroupWidgetFactory
override fun label(text: String, styleName: String, init: VisLabel.(Actor) -> Unit): VisLabel = super.label(text, styleName, init) as VisLabel
```
And then usage
```kotlin
table {
  label("A") {
    val a: VisLabel = this
    val b: Cell<*> = it
  }
}

horizontalGroup {
  label("A") {
    val a: VisLabel = this
    val b: Actor = it
  }
}
```
The question is, do we really want to keep this current implementation instead of doing it `ktx-scene2d` way?

**Comment by czyzby** [comment]
I don't think inlined builder methods are a huge advantage over regular lambdas in this case, since the UI is usually built once and the additional cost would be pretty much negligible. Rewriting a module that _just works_ is a huge undertaking for little gain. That said, it would be nice if the two libraries could share some common code - `ktx-vis` seems like a natural extension of `ktx-scene2d`.

Estimate how much work it would take to add lambda parameters and to completely switch to `ktx-scene2d` approach of inlined blocks. Find out if any APIs would be simplified in the process. I honestly don't mind if the two modules are slightly different and mutually exclusive, and I certainly don't want you working on something that you don't think makes sense.

**Comment by czyzby** [comment]
To be honest, now that I've investigated Kotlin 1.1 features, I consider `ktx-scene2d` incomplete. You can proceed with the estimation after #46 and #48 are done. I'll try to make it this weekend.

**Comment by czyzby** [comment]
Thanks, I'm glad that now `ktx-scene2d` and `ktx-vis` APIs are pretty much consistent. I think we can close this issue after updating `CHANGELOG.md`.

**Comment by kotcrab** [comment]
Yup, though implementation is quite different.

Some `CHANGELOG.md` points apply both to `ktx-vis` and `ktx-scene2d`. I guess we can mention two modules for one point?

**Comment by kotcrab** [comment]
Updated changelog. @czyzby fell free to close.

**Comment by czyzby** [comment]
Thanks.
