### ISSUE TITLE
Coroutines support

### ISSUE THREAD

**Issue by czyzby** [czyzby/ktx#47]
- [x] Add `ktx-async` module.
- [x] Implement coroutine context for LibGDX applications that executes tasks on the main rendering thread, using `Gdx.app.postRunnable` to resume coroutines executed on other threads.
- [x] Implement utility functions for asynchronous tasks based on coroutines executed on a configurable `AsyncExecutor` instance.
- [x] Add `HttpRequest` utilities based on coroutines.
- [x] Simplify LibGDX `Timer` API. Currently it does not support lambdas.
- [x] Add suspending `delay` method, which does not block the main rendering thread using LibGDX `Timer`.
- [x] `skipFrame` suspending method that resumes on the next frame using `Gdx.app.postRunnable` API.
- [x] Implement tasks cancellation.
- [x] Documentation with usage examples.

---

Implement `ktx-async` module with asynchronous operations utilities and Kotlin 1.1 coroutines support.

**Comment by czyzby** [comment]
@kotcrab Sweet. LibGDX `HttpResponse` implementation is not thread-safe and [does not care if the underlying connection was closed, silently ignoring all exceptions](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/net/NetJavaImpl.java#L57-L91). Here I was, wondering why my implementation of asynchronous HTTP requests always returns empty content - I debugged LibGDX code and now I'm surprised it even works in the first place.

**Comment by czyzby** [comment]
@sreich @kotcrab How should I call the most commonly used method that gives you access to KTX coroutines context and allows to execute code on the main rendering thread? `onMainThread`, `execute`?

**Comment by kotcrab** [comment]
No idea. `execute` is too vague in my opinion. `onMainThread` or `onGdxThread` is ok-ish. I probably like most `postRunnable`, same as `Gdx.app.postRunnable`. Maybe just `post` but that seems vague if it's a global method.

**Comment by czyzby** [comment]
`postRunnable` might be misleading, as coroutine can be executed on the same thread right after you start it, and it can create more than a single task objects under the hood. `onMainThread` isn't ideal either, as your coroutine might never do anything significant on the main thread. Maybe something more explicit like `gdxCoroutine` or `ktxCoroutine`?

**Comment by kotcrab** [comment]
I see. Nothing really strikes my mind though. I guess something like `ktxAsync` is not ideal either?

**Comment by czyzby** [comment]
Not ideal, but simple and obvious. Not only does it match the module name, but also does not suggest where the code is executed (`onMainThread`) - only that it can be executed asynchronously. It's so trivial to add such method or simply use `KtxAsync` context directly with `launch`, that I don't think `ktxAsync` method will be harmful.

**Comment by raincole** [comment]
I personally +1 for `onMainThread` because when one use this kind of behavior he has to be aware of which thread the tasks will be executed.

Or `onNextFrame`, maybe? "Frame" sort of implies the thread that can render frames, a.k.a. main thread.

**Comment by czyzby** [comment]
But that's the thing: it does not have to be executed on the main thread. If you're using coroutines in the first place, chances are half of the instructions will be executed elsewhere. Only the processing of async operations results and non-suspending methods are invoked on the rendering thread. 

```Kotlin
onMainThread {
  val httpResponse = httpRequest(url = "example.com", method = "GET") // Net implementation executor.
  delay(1) // Timer.
  val result = asynchronous { someTask() } // Context's AsyncExecutor. 
}

**Comment by sreich** [comment]
>Only the processing of async operations results and non-suspending methods are invoked on the rendering thread

I don't think you meant to say "non suspending methods". Suspending methods can be on any thread including the render thread and it can be useful to use them on the rendering thread to mask state.

Or am I misunderstanding here?

**Comment by czyzby** [comment]
That's right, I oversimplified. I should have said _non-suspending methods and suspending methods that **can** be executed on the main thread_. `KtxAsync` context always tries to execute everything on the main rendering thread, besides the obvious cases where the actual work is delegated other threads.

**Comment by czyzby** [comment]
@kotcrab @sreich @raincole @MrPlow442 Can you take a look at the new module implementation and API? #57 I want your approval before merging and releasing this.

**Comment by raincole** [comment]
I'm heading for ludum dare this weekend! If no one else does I can help review it next week.

**Comment by czyzby** [comment]
It's OK. Good luck. ; )

**Comment by czyzby** [comment]
@kotcrab Thanks for the #57 code review. There's already a _lot_ of changes since the last version, so I'm going to release 1.9.6-b2 now and move KTX to the new repository. Coroutines-based asset loader is postponed to the next release.
